name       : perl-gtk2
version    : '1.24993'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/X/XA/XAOC/Gtk2-1.24993.tar.gz : 49c443743b2eefe11a768002724f7f6a4c48efc94ff3cd3a559fb7e7b693c967
license    : LGPL-2.1-or-later
component  : programming.perl
summary    : Perl bindings for Gtk+ 2.x
description: |
    Perl bindings for Gtk+ 2.x
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-2.0)
    - perl-cairo
    - perl-glib
    - perl-pango
    - perl-extutils-depends
    - perl-extutils-pkgconfig
rundeps    :
    - perl-cairo
    - perl-glib
    - perl-pango
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
#check      : |
#    %perl_build test
