name       : perl-gtk2
version    : 1.24992
release    : 2
source     :
    - https://netcologne.dl.sourceforge.net/project/gtk2-perl/Gtk2/1.24992/Gtk2-1.24992.tar.gz : a2ed6902f7f29f7c8dddbe58119589f433252a12132c295c54afbac587cc8480
license    : LGPL-2.1
component  : programming.perl
summary    : Perl bindings for Gtk+ 2.x
description: |
    Perl bindings for Gtk+ 2.x
builddeps  :
    - pkgconfig(cairo)
    - pkgconfig(gtk+-2.0)
    - perl-cairo
    - perl-glib
    - perl-pango
    - perl-extutils-depends
    - perl-extutils-pkgconfig
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
